spring:
  data:
    mongodb:
      uri: mongodb+srv://vienna_001:U65zzmUeutDP2zF@zoockathon0-e3coy.gcp.mongodb.net/test?retryWrites=true&w=majority
      database: wildtales
  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 10MB
      max-file-size: 10MB

cloudinary:
  cloud-name: dnfs1zgww
  api-key: 875783843122147
  api-secret: ZDfxRrED4zMv1NdqlmIBHfmVlio
